---
title: "Other CV related stuff"
---

## Languges

- Danish

- English: americans think I'm british. Brits know I'm not.
- German: Fair reading comprehension, especially technical texts. Understand
spoken german - if "Hochdeutsch" is spoken slowly. Speaks it well enough to
order at restaurants.
- French: I can read and understand chemical literature in french. I do not dare
order at restaurants.

## IT 

In the traditional understanding of that word, I am a superuser of Microsoft Office.

I teach programming in R and have basic knowledge of Python. 

Daily user of Linux, know regular expressions and SQL. Run my own webserver.


## Private
Born June 20th 1974, married to Kristian, living i Rødovre.

Interests include politics and societal matters in general, molecular gastronomy, digital electronics, the history of science, shooting, swimming, Star Trek in particular and science fiction in general.


## Talks

Og kurser udenfor min egentlige arbejdsbeskrivelse



*1. marts 2012* - "Fagspecifikke databaser contra Web scale discovery, og om
brugen af sidstnævnte kan spores  i statistikkerne".
30 minutters oplæg på temadagen "Alt i ét? Overvejelser og praktiske erfaringer med Web Scale Discovery i Danmark".
Arrangeret af DFs forum for E-ressourcer. Den Sorte Diamant, København

*21. februar 2012* - "Causeri over e-bogen og e-bogslæsere". 1 times foredrag for Bibliotekarforeningens seniorgruppe. Det Kongelige Bibliotek, København.

*27. oktober 2011* - oplæg til forskningsbibliotekardag i Helsinki
*2. september 2011* - to-timers oplæg og debat på fredericia bibliotek
*24. maj 2011* - oplæg til møde i erhversskolernes biblioteksorening - hindsgavl
*11. marts 2011* oplæg om ebøger, CBS biblioteket
*24. februar 2011* - oplæg om ebøgernes historie og (u)muligheder. temadag på københavns kommunebiblioteker
*27. januar 2011* - DF-vinterinternat om ebøger


2. december 2010 E-bøger - før og lige nu. Temadag om E-bøger på Gentofte Centralbibliotek, Hellerup
16. november 2010 E-bøger på KB - hype, men vejen frem? Foredag på forskningsnet konference 2010, Comwell Middelfart
9. november 2010 - Chair ved debat på uddannelsesforum 2010, bellacenteret (Dorthe Toft)
27. juli 2010 - indslag om e-bøger i TV-avisen
15. juni 2010 - oplæg om (e)bøgernes fremtid ved åbning af emidialab på Odense Centralbibliotek
19. maj 2010 Oplæg om ebogens historie i forbindelse med projektet "Library bypass", Fredericia (og hvornår var det så at dagen om library bypass blev holdt?)
6. maj 2010- foredrag om ebøger - gå-hjem-møde på Statsbiblioteket
9. apirl  2010 -  Ebogserfaringer, oplæg for Faggruppen for medicinsk information. Glostrup Sygehus.
7. april 2010 - E-bøger, status, muligheder og begrænsninger. Oplæg og paneldebat ved semesterseminar på SDU.
23. marts 2010 - So Ein Ding, DR2 om vores udbud af ebøger og udlån af ebogslæsere
12. februar 2010-  oplæg for TORS om ebogslæsere, Værløse


17. november 2009 foredrag om ebøger for minibib, københavn
26. maj 2009 - foredrag om ebøger - hovedbiblioteket Guldborgsund
30. marts 2009-  foredrag om ebøger, BF, frederiksberg.



Foredrag og oplæg
 
Folkeuniversitetet, foredragsserie om Science og Science-fiction: ”Kemien mellem stjernerne” (Den sorte diamant, København) 19. oktober, 2007
 
Formidling i nye medier, seminar 21. juni 2007 (Den sorte diamant, København), ”InfoGalleriet, Den fremskudte formidling”

Temadag om e-bøger, møde i Bibliotekar Forbundets Statsgruppe 17. november 2008 (BFs hus) ”Teknik: Software og hardware – læsere”

Kreativ anvendelse af data, Temadag i DEFF, (CBS, Kilen, frederiksberg): ”Hybride data og Virtuelle verdener” 12/10-07
