project:
  type: website
  output-dir: docs

website:
  title: "Christian Knudsen"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: CV
        menu:
          - href: work
            text: Work
          - href: education
            text: Education
          - href: organisations
            text: Organisationer
          - href: notes
            text: Noter and stuff
          - href: other
            text: Other stuff
      - href: stuff
        text: Stuff
  page-footer:
    left: "(c) Christian Knudsen, 2023 –. "
  twitter-card: true
  open-graph: true
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: source