---
title: "Adfærdskodeks"
subtitle: "Eller: Code of Conduct for voksne"
author: "Christian Knudsen"
visible: "false" # sæt til noget andet når oplægget/noten er færdigt
categories:
  - kategori 1
  - kategori 2
date: 2025-06-10
toc: true
image: ""
---

I mange sammenhænge er der åbenbart brug for en adfærdskodeks. Jeg tror, det i 
bund og grund handler om at behandle folks egne usikkerheder, og en generel 
måde at tilbyde ro til folk der er for usikre til simpelthen at bede 
(andre) folk om at opføre sig ordentligt.

Adfærdskodekser har tendens til at være meget lange, og de bliver kun længere. 
For måderne, hvorpå folk kan opføre sig dårligt, er legio.

I nogle projekter har jeg defineret adfærdskodekset meget kort:

Noli turbare circulos meos. Eller nogen andres.

Hvis du gør det, vil vi udslette, slette, låse, lukke, forbyde eller hvad der nu er nødvendigt, for at have uforstyrrede cirkler.

Men jeg har fundet en lidt længere version, der pænt kombinerer "den gyldne regel" og en stoisk tilgang til projekter:

# Adfærdskodeks for Voksne

## 1. Velviljeprincippet

Når du interagerer med mennesker omkring dette projekt, så prøv at antage det 
bedste om dem. Hvis noget virker stødende, så start med at antage, at du har 
misforstået. Behandl andre, som du ville ønske, at de behandlede dig.

## 2. Handlingsprincippet

Vi har alle evnen til at vælge, hvordan vi føler, samt hvordan vi reagerer. 
Andre mennesker kan ikke "gøre" dig ked af det eller "såre" dine følelser, 
medmindre du lader dem. Vælg at tage ansvar for din egen mentale tilstand og 
udøv din handlefrihed. Giv ikke andre mennesker magt over dig, som de ikke har; 
magten til at udløse en følelsesmæssig reaktion i dig. 
Du har evnen til at ignorere det meste. Brug den.

## 3. Fokusprincippet

Dette er ikke stedet for social eller politisk aktivisme. Når du interagerer med 
mennesker omkring dette projekt, så hold dig til emnet. Mens du er her, er den 
eneste sag, du skal kæmpe for, projektets succes. Ingen distraktioner.

## Håndhævelse

En eller flere advarsler hurtigt opfulgt af midlertidige eller permanente forbud 
for at minimere forstyrrelser af fokus på det meritokratiske projekt med softwareudvikling.

##### Kilde
Forfatter: Not Governor
URL: https://gitbanned.com/NotGovernor/Code_of_Adult_Conduct/src/branch/master/README.md
