---
title: "Noter til historisk rundvisning NA49"
subtitle: "indsæt subtitle"
author: "Christian Knudsen"
visible: "false" # sæt til noget andet når oplægget/noten er færdigt
categories:
  - kategori 1
  - kategori 2
date: 2025-11-06
toc: true
image: ""
---

Universitetet grundlægges 1479 - og tre år senere i 1482, blev universitetsbiblioteket 
grundlagt, da professor dr. jur. Peder Albertsen forærede biblioteket et "medicinsk værk og nogle flere bøger". Legenden går at det var i alt ca. 7, og det var mange bøger den gang. 
1497 forærer han yderligere 24 bøger til universitetsbiblioteket. Vi ved ikke hvor
biblioteket boede. Der kom flere boggaver gennem 1500 tallet, men universitetet 
gjorde ikke meget selv for at indsamle bøger. 

Efter reformationen i 1536 blev der indsamlet bøger fra kirker og klostre i hele landet - som
blev deponeret på biblioteket. Og på et eller andet tidspunkt - det vides vist ikke
præcist hvornår, rykkede biblioteket til Helligåndshuset. 

Den ældst kendte fundats stammer fra 1539. Bemandingen bestod i en student, der skulle åbne, lukke
og rydde op - når nogen havde brug for biblioteket. 

1543 rykkede man ind i st rochi kapel ved vor frue kirke til de mest benyttede bøger. Hovedsamlingen
var stadig i helligåndshuset. 

Første selvstændige bygning fik biblioteket i 1553 i liberihuset - der hvor universitetets 
hovedbygning ligger i dag. Der blev vil til 1652. Bestanden ved indgangen til 1600-tallet har 
været på ca. 1100 bind. 

i 1608-24 indgik de kongelige historiografers materialer, og UB var derefter det centrale sted
for forskning i danmakrs historie - og var i praksis nationalbibliotek.

Chr IV byggede trinitatis kirke som multifunktions forsknings bygning. Observatorium i rundetårn,
universitetskirke, og på loftet over kirken bibliotek.

I 1653 blev de første biblioteksforelæsninger holdt - det var nødvendigt for opstilingen var
organiseret efter hvem der havde foræret ub bøgerne, ikke efter emne.

1728 - det taler vi stadig om - Kbhs første store brand. UB med ca. 30000 bind gik tabt. Herunder
helt uerstattelige håndskrifter. Underbibliotearen skrev: "I Bibliotheket oven på Trinitatis Kirke vare mange Ting, som Verden nu ikke mere eier; hvilken Skade kan ikke afhielpes"

Trinitatis kirke blev genopbygget i 1731 og bibliotekssalen genindrettet. Men uden bøger. 
Universitetet begyndte at købe bøger! og dublet overførsler fra Det kongelige bibliotek og andre 
gaver fra kongen fyldte hullet ud.

Ny fundats i 1732 - hjemlån var forbudt - undtagen for professorer. Hjemlån for studenter blev
tilladt i 1788. 

1849 startedes et anskaffelsessamarbejde mellem KB, UB og Det Classenske Bibliotek. 

KB oprtet 1663 - primæt med administration, geografi, jura, hitorie, teologi og litteratur.

Det klassenske bibliotek blev oprettet 1795. En bestemmelse i generalmajor J.F. Classens testamente.
Det var privat, men meed offentlig adgang - naturhistorie, medicin, veterinær og jordbrugslitteratur.

Her finder vi kerne til fagdelingen i UB senere.

1861 blev Herholdts biblioteksbygning på fiolstræde bygget og taget i brug.

1867 blev hovedparten af Det Classenske Bibliotek overført til UB - som fik navnet:
"Universitetsbibliotekt og det dermed forenede Classenske Bibliotek".

1926 indførtes systemet med hovedfagbiblioteker. UB blev et sådant for matematik, natur- og lægevidenskab.
Det katalog der blev indført den gang var stadig i brug da jeg blev ansat i 2003. 

Som følge af systemet blev samlingerne delt - ub overtog dele af kbs litteratur, og kb fik overført
håndskrifter og inkunabler.

1938 blev UB delt i to afdelinger, UB1 og UB2. Reelt to nye selvstændige biblioteker. 

UB1 blev i fiolstræde - UB2 flyttede ud på Nørre alle hvor vi bor i dag. 
Arkitekt var Kr. Varming. En moderne bygning med læsesal også til studenterne, studieværelser,
og bogtårn. 

Perfekt placering - lige ved siden af universitets institutter og rigshospitalet. 
Ved indvielsen var kun fem etager af tårnet var fyldt, men der var 10 klar. Og bygningen
blev hurtigt for lille. 
Man prøvede flere gange at få penge til udvidelse, bla 1963, men først i 1989 lykkedes det med 
den nuværende grundplan. 

Udsmykningen i studenterlæsesalen blev indviet i 1940 - kunstner Andreas Friis. 

Tilbygningen blev taget i brug i 1989  - arkitekt Eva og Nils Koppel og Gert Edstrand.
