---
title: "Frivilligt og organisatorisk arbejde"
---


### Copenhagen pride 
- **Okt 2014 -** Revisor/organisatorisk tilsynsførende.
- **Feb 2008 - Oct 2014** Medlem af bestyrelsen - kasserer.  
Overtog en kriseramt økonomi med en egenkapital på 600 kr. Efterlod den med en omsætning på +1 Mkr og 100Kkr i egenkapital.


### Happy Copenhagen 
- **May 2015 - May 2023** Medlem af bestyrelsen, næstformand og formand i forskellige perioder.  
Udpeget af Copenhagen Pride til ledelsen af foreningen der blev stiftet af Copenhagen Pride og Pan Idræt, med det
formål at få World Pride og Eurogames til København i 2021. Og derefter afvikle begge arrangementer.


### Radikale venstre
Rødovre, 

- **Jul. 2023 -- Dec. 2023** Rødovre-Herlev Bestyrelsen

- **Aug. 2007 - May 2012** Storkredsformand københavns omegn.

- **? til Jul. 2023** Bestyrelsesmedlem, i perioder kasserer og formand  Rødovre Radikale Venstre

Hovedbestyrelsen

Organisationsnetværket

Hvidovre radikale venstre - revisor

### TR

### Dansk Selskab for Historisk Kemi
- **Nov 2014 -** Kasserer
- **Nov 2006 - nov. 2014**. Sekretær


### Kollegie Konsulent Ordningen
- **Feb. 99 – feb. 02** Kollegiekonsulent Ordningen, KKO  
Formand for Kollegiekonsulent Ordningen - forening tilknyttet studiemiljøet
ved DTU, som udførte frivilligt arbejde inden for organisationsudvikling, konfliktløsning, forhandling, samt tilbyder psykologisk bistand. Havde særligt
ansvar for ledelsen af vores ansatte konsulent, samt kommunikations- og strategiprocesser.

### Polyteknisk forening
- **1995 – 2001** Polyteknisk Forening
Aktiv i studenterorganisationen på DTU, i 1998, som medlem af foreningens
bestyrelse på fuld tid. Jeg havde her ansvaret for at koordinere foreningens
arbejde i de kollegiale organer, herunder at definere foreningens politiske linie
samt at rekruttere og motivere frivillige til dette arbejde. Derudover indgik jeg
i ledelsen af foreningens erhvervsaktiviteter.

- **Jan. 99 – dec. 99** Konsistorium, DTU
Medlem af konsistorium på DTU.  
Mine fokusområder var institutionens økonomi og forskning.
- **Jan. 97 – dec. 98** Kandidatstudienævnet, DTU  
Øverste myndighed hvad angik civilingeniøruddannelsen på DTU. Mine fokusområder var undervisningsevaluering og integration af forskning og undervisning.


### DFFU - forum for e-ressourcer
***? - **

### DOAJ
- **2019-09-24 - 2025-03-26** Council  
https://blog.doaj.org/2019/09/24/the-community-has-chosen-introducing-the-new-doaj-council/

### Helsinge skakklub
**? - ? **
Fra starten - der gik jeg i gymnasiet. Fortsatte noget tid efter start på DTU.

### Frederiksborg Amatørdanserklub - SRØ
**? - ? ** det var i 3. g. jeg fortsætter til - lidt før 1998? for jeg er der ikke 
da jeg sidder i bestyrelsen.

## Frivilligt arbejde uden titler og poster
- **Sep. 02 – apr. 03** Symposiet ”Ledelse af projekter, udvid din kompetence”

Adminstrativ og praktisk deltager i Foreningen for Dansk Projektledelse i

forbindelse med Symposiet Projektledelse 2003. Jeg deltog i hele det prak-
tiske arrangement, samt i udvalgte dele af det faglige arrangement, bl.a. ved

Reviewlæsning af de indsendte artikler.

### NGO-forum'95 Social Summit
- **Mar. 1995** Volunteering at the computerhub.

### Danske Studerendes Fællesråd
- **Feb. 01 – nov. 02** Danske Studerendes Fællesråd, DSF

Medlem af Økonomiudvalget. Rådgivende organ vedrørende økonomiske
forhold i DSF. Jeg har her specielt arbejdet med budgetlægning og -opfølgning
samt personaleforhold. De datoer virker underligere. UPU?
beretninger fra pf?