---
title: "Organisational work"
---


### Copenhagen pride 
- **Feb 2014 - current** Elected auditor, later in a more broad role as 
Organisational Supervisor.
- **Feb 2008 - Oct 2014** Member of the board, treasurer. 
- **Aug 2006 - Aug 2009** In charge of organising the parade

### Happy copenhagen 
**May 2015 - May 2023** Member of the board of directors, appointed by 
Copenhagen Pride. I served in various positions, including Vice Chairperson 
of the Board and Chairperson of the Board.


### Radikale venstre
Rødovre, 

**Jul. 2023 -- Dec. 2023** rødovre-herlev

**2007 - may 2012** Storkredsformand københavns omegn.



Hvidovre radikale venstre - revisor

### TR

### Danish Society for Historic Chemistry
**Nov 2006 - current** Member of the board, and secretary until Nov. 2014. From
Nov. 2014 as treasurer.

### KKO
**Feb. 99 – feb. 02** Kollegiekonsulent Ordningen, KKO

Chairman of "Kollegiekonsulent Ordningen" - An association affiliated with the 
student community at DTU that carried out voluntary work in organizational 
development, conflict resolution, negotiation, and offered psychological support. 
I had particular responsibility for managing our employed consultant, as well 
as communication and strategy processes.

### Polyteknisk forening
**1995 – 2001** Polyteknisk Forening
Aktiv i studenterorganisationen på DTU, i 1998, som medlem af foreningens
bestyrelse på fuld tid. Jeg havde her ansvaret for at koordinere foreningens
arbejde i de kollegiale organer, herunder at definere foreningens politiske linie
samt at rekruttere og motivere frivillige til dette arbejde. Derudover indgik jeg
i ledelsen af foreningens erhvervsaktiviteter.

**Jan. 99 – dec. 99** Konsistorium, DTU
Medlem af konsistorium på DTU. Mine fokusområder var institutionens økonomi og forskning.


**Jan. 97 – dec. 98** Kandidatstudienævnet, DTU

Øverste myndighed hvad angik civilingeniøruddannelsen på DTU. Mine fokusområder var undervisningsevaluering og integration af forskning og undervisning.


### DFFU - forum for e-ressourcer
**? - **

### DOAJ
**? - 2025-03-26** Advisory board 

### Helsinge skakklub
**? - ? **
Fra starten - der gik jeg i gymnasiet. Fortsatte noget tid efter start på dtu.

### FAK - SRØ
**1993 - ? ** Fra generalforsamlingen da jeg gik i tredie g.
Til engang i sidste halvdel af 1990'erne.

## Other organizational experience. Or: Voluntary work without a dedicated title or position.

**Sep. 02 – apr. 03** Symposiet ”Ledelse af projekter, udvid din kompetence”

Adminstrativ og praktisk deltager i Foreningen for Dansk Projektledelse i

forbindelse med Symposiet Projektledelse 2003. Jeg deltog i hele det prak-
tiske arrangement, samt i udvalgte dele af det faglige arrangement, bl.a. ved

reviewlæsning af de indsendte artikler.

### NGO-forum'95 Social Summit
**Mar. 1995** Volunteering at the computerhub.


*Feb. 01 – nov. 02* Danske Studerendes Fællesråd, DSF - 

Medlem af Økonomiudvalget. Rådgivende organ vedrørende økonomiske
forhold i DSF. Jeg har her specielt arbejdet med budgetlægning og -opfølgning
samt personaleforhold. De datoer virker underligere.








