---
title: "Education"
---

An attempt at a complete list. Including stuff that is not necessarily relevant
for anything.

## Formal Eduction

### University of Copenhagen

**August 2023:** [Introduction to Social Data Science](https://web.archive.org/web/20240112121316/https://kurser.ku.dk/course/a%C3%98kk08216u/). Summerschool at the Department of Economics.

### Copenhagen Business School

**Aug. -- dec. 2009** Erhversret
**Jan. -- Apr. 2010** Udvidet erhvervsret
**Jan. -- Jun. 2013** Samfundsøkonomi
- *Forvaltningsret*
**Aug. -- dec. 2008** Dataanalyse

### AMU

**Feb. -- mar. 2005** Gaschromatografi 

AMU-kursus i praktisk anvendelse af kapillar gaschromatografi. 


**Jan. -- feb.  2005**  HPLC operatør

AMU-kursus i praktisk anvendelse af HPLC.


### DTU

**February 1994 -- February 2002**: Cand. Polyt. (M.Sci.Eng) fagprofil Pure and Applied Chemistry

### Helsinge Amts Gymnasium

**August 1990 -- Juni 1993**: Matematisk studentereksamen.

### Helsinge Realskole
**Aug. 1980 -- Juni 1990**

## Certifications

FEANI

Basic GMP

Isotopteknik

Carpentries

## Not so formal education

**Sep. 2000 -- dec. 2000**  Studieophold i Grækenland

Kemisk institut på universitetet i Patras, Grækenland. Jeg foretog spektroskopiske
(Raman og VIS/NIR) undersøgelser af modeller af industrielt anvendte
svovlsyrekatalysatorer, med henblik på opnåelse af viden om
komplekskemien og redox-forholdene i disse modeller.


## Kurser
**Mar. 2005**  Kvalificering og validering af produktionsudstyr

Tre dages kursus på Pharmakon. Udstyrskvalificering, valideringsplanlægning, dokumentation og myndighedsinspektioner.

 
**Nov. 2003**  Patentdag for kemikere

Fagligt møde om patentering og patenter udbudt af Kemiingeniørgruppen under Ingeniørforeningen i Danmark.

**Jun. 2003** GMP grundkursus

Kursus udbudt af Kemiingeniørgruppen under Ingeniørforeningen i Danmark. Kurset 
gennemgik ved forelæsning og øvelser principperne for GMP herunder produktion,
validering, dokumentation og QA/QC.

IT projektlederuddannelse - Mannax, KB.

Excelkurser fra 4D

**Jun. 2024** QGIS

GIS-kursus ved SC Datalab ved Københavns Universitet.

**May-Jun. 2024** Førsteårspædagogik
