---
title: "Interessante artikler"
subtitle: "Der viser ting som må være forkerte"
author: "Christian Knudsen"
visible: "true" 
categories:
  - Referencer
date: 2025-05-07
toc: true
image: ""
---

Blot en samling af links til rapporter, artikler og andet godt.


[Ændringer i prøveformer giver øget kønsforskel i folkeskolens eksamener](https://web.archive.org/web/20251206085940/https://rockwoolfonden.dk/udgivelser/aendringer-i-proeveformer-giver-oeget-koensforskel-i-folkeskolens-eksamener/). Fra Rockwool fonden. Der ses ingen kønsforskel i hvad eleverne
faktisk kan. Men prøveformen favoriserer pigerne, der får systematisk højere 
karakterer end de ligeså kvalificerede drenge.

[Nogle elever får lave karakterer trods fint fagligt niveau](https://web.archive.org/web/20260113053811/https://rockwoolfonden.dk/udgivelser/nogle-elever-faar-lave-karakterer-trods-fint-fagligt-niveau/). Fra Rockwool fonden. De nogen elever, der får lavere karakterer
end deres lige så dygtige klassekammerater, har det til fælles at de er drenge. 


[Kønsforskelle fra fødsel til død](https://web.archive.org/web/20251215075859/https://rockwoolfonden.dk/udgivelser/koensforskelle-fra-foedsel-til-doed-drenge-og-maend-klarer-sig-daarligere-end-piger-og-kvinder-undtagen-paa-arbejdsmarkedet/). 
Fra Rockwool fonden. Af 23 livsbegivenheder fra fødsel til død klarer mænd sig ringere
end kvinder på 3 punkter. På 3 punkter er der ligestilling. På 17 klarer 
kvinder sig markant bedre.

[Udsatte borgere dør oftere af fortvivlelsesdødsfald](https://web.archive.org/web/20251014163228/https://rockwoolfonden.dk/udgivelser/udsatte-borgere-doer-oftere-af-fortvivlelsesdoedsfald/). Fra Rockwool fonden. Udsatte borgere dør oftere
af selvmord, alkohol og andet misbrug. Mænd i alderen 45-64 dør dobbelt så hyppigt
som kvinder i samme aldersgruppe.

[Nu er det især mænd, der diskrimineres, når de søger job](https://web.archive.org/web/20250917173955/https://dm.dk/akademikerbladet/aktuelt/2024/januar/nu-er-det-isaer-maend-der-diskrimineres-naar-de-soeger-job/). Akademikerbladet kan fortælle at man ikke længere kan få øje på
at kvinder skulle blive diskrimineret når de søger arbejde i traditionelle mandefag.

Eller, som artiklen formulerer det "Med andre ord står mænd samlet set dårligere i jobsøgningen end kvinder gør."

Den oprindelige forskning kan findes her:
[On the trajectory of discrimination: A meta-analysis and forecasting survey capturing 44 years of field experiments on gender and hiring decisions](https://web.archive.org/web/20231111073106/https://www.sciencedirect.com/science/article/pii/S0749597823000560).
Schaerer, M. et al. Organizational Behavior and Human Decision Processes, Volume 179,
2023, 104280.


[HPV vaccine Session introduction and key questions](https://web.archive.org/web/20241126232745/https://cdn.who.int/media/docs/default-source/immunization/position_paper_documents/human-papillomavirus-(hpv)/hpv-vaccine-session-introduction-key-questions-april-2022.pdf). WHOs officielle position var (og er formentlig stadig) at drenge i Danmark (og andre lande) ikke skal have adgang til vacciner der forebygger 
kræft, før alle kvinder i alle andre lande har fået adgang til vaccinen.


[Experimental Evidence on the Acceptance of Males Falling Behind](https://doi.org/10.1093/jeea/jvaf016). Eksperimentel undersøgelse der dokumenterer, at holdningen (blandt respondenterne) er, at hvis mænd klarer sig dårligt, så er det deres egen skyld.
Men hvis kvinder klarer sig dårligt, så skal de have hjælp. Gerne på 
bekostning af mænd der har klaret sig bedre.

[Mere populær gennemgang i Weekendavisen.](https://web.archive.org/web/20250815200747/https://www.weekendavisen.dk/ideer/det-dovne-koen)

## En lille samling af beslægtede artikler
[Orchestrating Impartiality: The Impact of "Blind" Auditions on Female Musicians](https://web.archive.org/web/20260129024738/https://www.aeaweb.org/articles?id=10.1257/aer.90.4.715). Den originale artikel fra 2000, der viste, at hvis auditions til orkestre sker bag et forhæng, så bedømmelsesudvalget ikke kender musikerens køn, så ansættes der flere kvinder i orkestrene. 
Den relative succes for kvinder i auditions er andelen af kvinder der ansættes minus andelen af mænd der ansættes. Er værdierne
positive, er der flere kvinder der er succesfulde. Er de negative, er der flere 
mænd der er succesfulde. Bemærk fortegnene i tabel 4.

Det førte til en række artikler om hvorfor blindede auditions er en god ide, blandt andet denne fra 2013:
[How blind auditions help orchestras to eliminate gender bias](https://web.archive.org/web/20131014121711/https://www.theguardian.com/women-in-leadership/2013/oct/14/blind-auditions-orchestras-gender-bias)

Og, nogle år senere, til artikler om hvorfor blindede auditions alligevel ikke var en god ide, eksempelvis denne fra 2020:
[To Make Orchestras More Diverse, End Blind Auditions](https://archive.md/OZNkg). Det viste sig at hvis man i rekrutteringsprocessen ikke kendte ansøgernes køn, kom ansættelsesudvalgene til at ansætte alene på kvalifikationer, hvilket ikke gav den ønskede diversitet.

Hvilket ikke burde være kommet som en overraskelse, fordi man i Australien i 2017 forsøgte sig med blindede ansøgninger ved ansættelser i det offentlige. Og var nødt til at stoppe forsøget undervejs, fordi det gav uønskede resultater:
[Blind recruitment trial to boost gender equality making things worse, study reveals](https://web.archive.org/web/20170701002727/https://www.abc.net.au/news/2017-06-30/bilnd-recruitment-trial-to-improve-gender-equality-failing-study/8664888)

## Tilbage til eksamener og den slags

[Boys lag behind: How teachers’ gender biases affect student achievement](https://www.sciencedirect.com/science/article/pii/S0272775718307714). Et dobbeltblindet eksperiment fra Frankring, hvor eksamensbesvarelser blev bedømt uden at examinator kendte elevens køn. Og hvor examinator kendte elevens køn.

[A gender gap in gender gaps: social norms and housework reporting](https://link.springer.com/article/10.1007/s00181-024-02710-z). Den illustrerer hvor vanskeligt det kan være at få data om folks adfærd. Når en interviewer interviewer kvinder om hvor mange timer de bruger på husligt arbejde får man et tal. Det tal er signifikant højere hvis intervieweren er kvinde, end hvis intervieweren er mand. Den forskel optræder ikke når mænd interviewes. Der er der ingen signifikant forskel, der afhænger af kønnet på intervieweren. Det er et kendt fænomen - når folk interviewes påvirkes deres svar af hvad de tror intervieweren vil høre. 

[Half of misogynistic tweets sent by women, study finds ](https://web.archive.org/web/20160602052747/https://www.theguardian.com/technology/2016/may/26/half-of-misogynistic-tweets-sent-by-women-study-finds). Det viser sig at ca. halvdelen af de misogyne tweets der blev tweetet (eller blev tweetet op til 2016), blev tweetet af kvinder.