---
title: "Parade ruter"
subtitle: "Den der oplevelse når aviserne skriver om noget du faktisk ved noget om."
author: "Christian Knudsen"
categories:
  - kategori 1
  - kategori 2
date: 2024-08-19
toc: true
image: ""
---

Jeg _elsker_ traditioner. De fleste i hvert fald. En af traditionerne hvert år
når der afholdes Copenhagen Pride, er mediehistorier om at paraden ikke går gennem
Nørrebro, fordi Priden er bange for at blive overfaldet af voldelige muslimer.

Den tradition er jeg pænt træt af...

Og ja, det er en god historie, og den lyder ganske plausibel. Der er mange steder
i byen hvor jeg ikke holder min mand i hånden efter mørkets frembrud. Det er _kun_
på Nørrebro vi ikke holder hinanden i hånden i dagslys. Det er der en grund til,
og den underkender jeg ikke.

For ja; koncentrationen af voldsparate homofober motiveret af deres religion er
nok noget større på Nørrebro end de fleste andre steder i landet. Jeg ved ikke om
der er effektive måder at måle det på, men vi ved også at vand er vådt uden at 
skulle måle det.

Men det er altså ikke _derfor_ paraden ikke går gennem Nørrebro. Og det er lidt
trættende at se de historier blive gentaget i medierne hvert år. 

Hvorfor er jeg træt af det? Det er ikke fordi jeg er en frelst radikal hallal-hippie
der mener vi skal lade være med at tale om homofobi blandt indvandrere (men jo, jeg 
er medlem af Radikale Venstre). 

Nej, årsagen til at jeg bliver træt af historien er, at jeg har været med til at 
arrangere netop paraden i en del år, og har siddet med i rummet hvor beslutningerne 
om ruten er blevet truffet. Jeg ved med andre ord _hvorfor_ ruten er 
blevet ændret. Og det er _ikke_ fordi vi har været bange. Faktisk tværtimod.

Og derfor er jeg ret træt af traditionen.

De vigtigste parametre der har styret ruten har været:

1. Behovet for at kunne opstille et signifikant to-cifret antal meget store lastbiler i rækkefølge på en startplads.
2. Det permanente vejarbejde i København.
3- Placeringen af større indfaldsveje, og politiets modvilje mod at blokere dem i længere tid ad gangen.
4. Risikoen for alvorlige ankelskader når 130 kg tunge, to meter høje dragquens stables op på 20 cm stilletter og skal gå adskellige kilometre på ikke specelt u-hullede veje.
5. Forskellen i den samarbejdsvilje Københavns og Frederiksbergs kommuner udviser.

Nå. 

Der har været pride-parader i København i mange år, i starten primært som 
Christopher Street Day (CSC) demonstrationer. De lå - og det er også den internationale
tradition - i juni. Hvorfor juni? Fordi det var den 28. juni 1969 at der opstod
optøjer ved baren "Stonewall Inn" i New York. 

Den fortælling er en smule mere kompliceret end de hagiografiske beskrivelser man ser en 
del steder. Og den har gennem årene været udsat for... Narrative justeringer efter 
hvad man politisk har syntes lød bedst. 
Det var eksempelvis ikke kun fordi New Yorks politi ikke kunne lide 
bøsser at baren regelmæssigt blev raidet. Det havde vist også en del at gøre med 
at den blev drevet af mafiaen. Og det første der blev kastet blev kastet af 
den lesbiske (Stormé DeLarverie)[https://en.wikipedia.org/wiki/Storm%C3%A9_DeLarverie].

Anyway, traditionen spredte sig. Også til Danmark. Og undervejs blev der 
etableret mere formelle organisationer, der organiserede "World Pride" og "Europride",
som fælles internationale begivenheder. En slags overbygninger på lokale, til dels
nationale, prides.

I forbindelse med at København var europæisk kulturby i 1996 fik man Europride til
byen. Det var min første pride, jeg lærte armbevægelserne til "YMCA" til en
koncert med The Village People, og nogle måneder senere havde jeg en overraskelse 
til mine forældre.

Vi skulle til en konfirmation i den indremissionske del af familien dagen efter,
så jeg overværede ikke paraden, og husker ikke ruten. 

Men fra 1999 har jeg styr på det:

* _1999 og 2000:_ Paraden startede ved Landbohøjskolen/KVL (i dag Frederiksberg Campus på KU). 
Den gik ad Vesterbrograde over H.C. Andersens Boulevard og Stormgade, til Christiansborg Slotsplads.

* _2001:_ Her var man nødt til at flytte sig. PostDanmark Rundt skulle slutte på
Frederiksberg, og det blev afgjort inden Priden fik søgt om tilladelse til ruten. 
Man ville gerne have fortsat på Frederiksberg, men var nødt til med kort varsel at 
flytte. Derfor startede man fra Borgmestervangen, og gik ad Nørrebrogade til 
Rådhuspladsen. 
Det år var jeg startet som frivillig i Priden. Jeg slæbte fustager for utaknemmelige
barejere, og vi hørte at der var lidt uroligheder hvor utilpassede unge kastede med 
ting. Så paraden blev ikke flyttet til Nørrebro fordi borgerne på Vesterbro kastede
med sten. Det skyldtes et cykelløb. 

* _2002:_ Paraden startede stadig på Borgmestervangen, og fulgte samme rute. På trods
af de forholdsvist beherskede uroligheder der havde været året før.

*_2003:_ Paraden havde vokseværk, og der begyndte at komme flere lastbiler med. 
Det gjorde pladsen på Borgmestervangen for trang, og startpladsen blev derfor 
flyttet til P-pladsen ved Nørrebrohallen - den der i dag hedder "Den Røde Plads".
Jeg var blevet træt af at slæbe fustager, og meldte mig som frivillig til paraden. 
Jeg havde en lidt ledende rolle, men det var stadig Pridens bestyrelse der havde den
egentlige ledelse af paraden. Der var en enkelt hændelse med nogle æg og et kanonslag
ved Assistens Kirkegård. Jeg var et par hundrede meter fra kanonslaget, og 
vurderingen var, at det var nogle autonome typer. Det er nemlig ikke kun 
utilpassede indvandrere der ikke kan lide priden. Utilpassede autonome kan heller
ikke lide den, fordi man skal betale for sine egne øl.

* _2004 og 2005:_ Her havde jeg en lidt mere ledende rolle, men stadig under kommando af
et bestyrelsesmedlem. Vi fulgte samme rute som i 2003, og der var ingen hændelser - 
ud over forvredne ankler - det er en risiko man løber når man placerer ret store, ret
høje, temmelig fulde, dragquens på meget høje stilletter.

* _2006:_ Nogen havde en fantastisk ide. Det ville se spektakulært hvis den store
farvestrålende parade gik rundt om Krinsen på Kgs. Nytorv. Man havde haft lyst til
det allerede i 2005, men fordi der havde været et par hændelser i 2003, udskød man
flytningen af ruten. Netop fordi man ikke ville lade sig skræmme væk fra Nørrebro.
Paraden skulle derfor gå fra Nordre Toldbod. Det var formelt stadig Pridens bestyrelse
der selv havde kommandoen, og planen var så at jeg skulle have det mere praktiske
ansvar på selve dagen. Det holdt ikke helt, for det bestyrelsesmedlem der havde
ansvaret blev væk. Han var sidst set bevægende sig i retning af Polen, og hvad den
historie nærmere handlede om, aner jeg ikke. Det korte af det lange var at min
gode veninde Rikke og jeg tirsdag eller onsdag som paraden skulle afvikles lørdag
overtog det fulde ansvar for paraden. Det gik sådan set fint nok, men det blæste
en pelikan på Toldboden, heliumballonerne stod vandret, og vi havde et par episoder
hvor folk lige akkurat ikke faldt i vandet. Det så vist heller ikke så imponerende
ud på Kgs. Nytorv som man havde forestillet sig. Under alle omstændighder blev
paraden det år flyttet fra Nørrebro. Ikke på grund af trusler, men på grund af 
ikke specielt gennemtænkte æstetiske overvejelser. Og flytningen skete et år 
eller to før det ellers ville være sket, netop fordi man ville trodse truslerne.

* _2007 og 2008:_ Den beherskede succes med Nordre Toldbod betød at vi rykkede
tilbage til Nørrebro. Det var ikke helt uproblematisk - og det havde det heller 
ikke været tidligere. Københavns Kommune stillede mere og mere skrammel op på den,
et af årene stod der et par paller med "De Gule Sider" der jeg havde planlagt at 
der skulle stå en lastbil. Nørrebrohallen var - ret forståeligt - ikke specielt
begejstret for den stand deres toiletter blev efterladt i. Stod der (og det gjorde der)
personbiler parkeret på pladsen, skulle vi selv kontakte politiet for at få dem
fjernet. For kommunen gjorde intet for at skilte med P-forbud i dagene op til.
Og så skulle alle lastbiler ind ad samme lille indkørsel ud på Mimersgade, hvilket
gjorde det ret komplekst at få dem vendt rigtigt og stillet op i den rækkefølge
vi ønskede. En yderligere komplikation var at vi selv skulle rydde op på pladsen
efterfølgende. Det var ikke nyt, men med en voksende parade, blev svineriet større,
samtidig med at det ikke blev lettere at finde frivillige der havde lyst til at forlade
festen på Rådhuspladsen for at rydde op på en P-plads.
Der var ingen ballade af betydning. Eller rettere, der var mindre
ballade end jeg ville forvente når man samler nogle tusinde feststemte mennesker på
et meget lille område og hælder alkohol på dem. 2007 var året jeg mødte min kommende
mand på pladsen. Han stod og var groggy efter for lidt søvn, og blev udstyret med
en kost og sat til at feje pladsen - the rest is history som man siger. 2008 var 
det sidste år jeg var ansvarlig for paraden. I praksis var det dog min efterfølger
Jesper der stod for det, for jeg var i mellemtiden blevet kasserer i Priden. Det er
en historie der er mindst lige så lang som denne og må vente til en anden gang. 

* _2009:_ Der skete flere ting dette år. Anlæggelsen af "Superkilen" der var
startet i 2004, var nået til Nørrebrohallens P-plads, og den skulle lige straks
omlægges til hvad der i dag kaldes "Den Røde Plads". Renoveringen stod endeligt
færdig i 2012. Der var også World Outgames i byen, og mængden af LGBTetc idrætsfolk
i byen, og dermed også i paraden var stor. Vi havde derfor en parade der var
større end ellers, og en startplads der var ved at blive omdannet til en byggeplads.
Samtidig havde Frederiksberg Kommune spyttet penge i World Outgames, og de ville
også have del i festlighederne. Frederiksberg var endda så flinke, at de 
tilbød at hjælpe med at fjerne biler fra området omkring deres rådhus, og de 
ville også stå for oprydningen bagefter. Valget var derfor let. Vores daværende
formand kiggede min efterfølger Jesper og jeg dybt i øjnene på et bestyrelsesmøde. Han 
meddelte at vi ikke skulle trues væk fra Nørrebro, og at han derfor kun ville 
acceptere at vi flyttede paraden hvis vi kunne fortælle ham at det var mindst to
år siden at der sidst havde været trusler mod paraden. Vi fortalte at det var 3 år siden
der sidst havde været noget. Og så flyttede vi tilbage til Frederiksberg hvor
det hele startede i 90'erne.

Vi ville ikke for alvor ændre ruten, og gik derfor stadig af Nørrebrogade. Det 
betød at vi skulle over Smallegade, for at gå ned af Falkoner Alle og Jagtvej. 
Det var ikke så galt. Værre var passagen af Ågade. Det var heldigvis ikke mit ansvar. 
Der er ikke mange afkørsler fra Bispeengbuen før krydset Ågade/Falkoner Alle,
og trafikken var et helvede. Ruten fortsatte ad Nørrebrogade, og passerede
Nørreport. Det havde den gjort før, men nogen husker måske at området omkring 
Nørreport Station blev renoveret i hvad der føltes som et årti. Så der var
udfordringer med at få lastbiler rundt i de smalle gader da paraden havde
passeret søerne.

* _2010 til 2014:_ Det havde været godt at have en startplads hvor den lokale kommune ikke
aktivt modarbejdede Paraden. Men politiet var ikke begejstrede for at vi igen 
skulle blokere Ågade. Og heller ikke fans af at vi blokerede al bustrafik omkring
landets største station i flere timer. Så ruten blev ændret til at gå ad
Frederiksberg Alle (hvor kommunen etablerede flagalle), videre ad Vesterbrogade,
til venstre ad Hammerichs Gade og via Jarmers Plads til Rådhuspladsen. H.c. Andersens 
Boulevard bliver stadig blokeret. Køen strækker sig helt ud på Amager. Men trafikken
er ikke helt så tung som den er på Ågade, og store dele af busserne til og fra
Nørreport kan køre uændret. 

* _2015 til 2019:_ Der skete ikke ændringer på ruten. Men. Jeg trådte ud af bestyrelsen
i 2014, efter seks år som kasserer. Jeg kan derfor ikke påstå at jeg var med til at 
træffe beslutninger om ruten i de år. Jeg blev valgt som revisor (med ret til at stikke
næsen i ALT), og hjalp også til under paraden. Så selvom jeg ikke ved det absolut,
er jeg meget sikker på at jeg havde hørt om det hvis man havde undladt ruteændringer 
på grund af trusler.

* _2020:_ Det var ikke trusler der holdt paraden væk fra Nørrebro det år. Det var Corona...

* _2021:_ Her var vi faktisk tilbage på Nørrebro! Det glemmer folk, inklusive mig selv.
I 2021 havde et internationalt mega-event i byen. Både Worldpride og Eurogames blev
afviklet samtidig. De dele var jeg en smule involveret i, da jeg fra 2015 havde siddet
i bestyrelsen (undervejs havde jeg endda været forperson), for den forening, Happy Copenhagen,
der var etableret for at planlægge og gennemføre de to arrangementer under fællesnavnet Copenhagen 2021.
Vi var stadig underlagt restriktioner, og selvom de fleste var løftet da vi nåede 
august, havde vi været nødt til at planlægge efter at de ikke blev. I stedet for
en stor parade, havde vi derfor 6 mindre "Pride Marches" der startede forskellige 
steder i byen, og mødtes i Fælledparken, hvor vi festede udendørs, i tre sektioner,
separeret med hegn. Startstederne var Højbro Plads, Rådhuspladsen, Israels Plads,
Churchillparken, Svanemøllen. Og "Den Sorte Plads", som jeg erindrer om ligger på 
Nørrebro. Selv gik jeg med fra Rådhuspladsen med Statsministeren og Kronprinsessen. 

* _2022 til 2024:_ Covid restriktionerne er løftet og vi er tilbage på Frederiksberg Rådhus for
at starte. 

Det blev langt. Men ruten _er_ også blevet ændret flere gange. Og der har været
_mange_ forskellige ting der har spillet ind på hvorfor den er blevet ændret som den
blev. Men muslimer med krumsabler har altså ikke været en af dem. 
Om noget betød de, vitterligt ret få trusler, at man holdt fast i Nørrebroruten længere, end man ellers ville have gjort.

Det der virkelig har betydet noget har været etableringen af Den Røde Plads, og det
forhold at Frederiksberg Kommune støtter med afspærring, lån af rådhus og oprydning. 

Jeg kan godt forstå, at der er mange, der ønsker ruten tilbage til Nørrebrogade.
Jeg synes selv det er en fantastisk rute. Jeg elskede at se indvandrekvinder i 
tørklæde vifte med regnbueflag. Og jeg elskede at se deres teenagesønner. Både dem
der ikke rigtig kunne finde ud af hvad de skulle gøre af sig selv fordi man ikke
laver ballade når mor står ved siden af. Og de der tydeligvis havde lyst til at 
deltage, men ikke turde springe ud. Og jeg mener oprigtigt at det noko er den del af København
der har størst brug for at blive eksponeret for paraden. 

Men ønsket om at paraden vender tilbage, kommer altså primært fra folk der ikke
selv har prøvet at skulle navigere 20 store lastbiler og +30.000 mennesker, ret
mange af dem på meget høje stilletter, sikkert gennem Københavns gader. 

Og så er der jo også den lille detalje at der faktisk er en parade på Nørrebrogade
hvert år, samme dag, blot arrangeret af nogen andre end Copenhagen Pride...
