---
title: "Publications and Talks"
---
## Publications

```{r setup, echo  = FALSE, warning=FALSE, message=FALSE, results="asis"}
library(bibtex)
library(RefManageR)
pubs <- ReadBib("publications.bib")
RefManageR::NoCite(pubs)
PrintBibliography(pubs, .opts = list(style = "html",
                                     bib.style = "authoryear"))
```


## Talks

* **3 November 2025** Lær at finde guldet i offentlige data. Morgenmøde i Dansk Magisterforening om brug af offentligt tilgængelige datasæt.
[slides](https://kubdatalab.github.io/DM-arrangement/#/title-slide)

* **8 October 2024** Naturvidenskabelig informationssøgning. 1½ times oplæg om søgning
efter naturvidenskabelige informationskilder for folkebibliotekarer ved arrangementet
"Har du styr på den naturvidenskabelige opgave? (Vest)" ved Vejle Bibliotek. 
[slides](https://christianknudsen.info/notes/20241003-natvid-lit-search/)
* **3 October 2024** Naturvidenskabelig informationssøgning. 1½ times oplæg om søgning
efter naturvidenskabelige informationskilder for folkebibliotekarer ved arrangementet
"Har du styr på den naturvidenskabelige opgave? (Øst)" ved Gentofte Bibliotek.
[slides](https://christianknudsen.info/notes/20241003-natvid-lit-search/)
* **13 January 2020** - "Naturvidenskabelig informationssøgning for bibliotekarer" Vejle bibliotek
* **25 November 2019** - "Naturvidenskabelig informationssøgning for bibliotekarer" Vejle bibliotek
* **1 June 2012** - “eBooks from a librarian view”. Oplæg ved LM eInformation Roadshow. Børsen, København
* **29 May 2012** - “eBøger på Københavns Universitetsbibliotek”. Oplæg ved LM eInformation Roadshow, Aros, Aarhus.
* **1 March 2012** "Fagspecifikke databaser contra Web scale discovery, og om
brugen af sidstnævnte kan spores  i statistikkerne".
30 minutters oplæg på temadagen "Alt i ét? Overvejelser og praktiske erfaringer med Web Scale Discovery i Danmark".
Arrangeret af DFs forum for E-ressourcer. Den Sorte Diamant, København
* **21 February 2012** "Causeri over e-bogen og e-bogslæsere". 1 times foredrag for Bibliotekarforeningens seniorgruppe. Det Kongelige Bibliotek, København.
* **27 October 2011** “eBooks in Denmark” - oplæg til forskningsbibliotekardag i Helsinki.
* **2 September 2011** to-timers oplæg og debat på fredericia bibliotek
* **24 May 2011** oplæg til møde i erhversskolernes biblioteksorening - hindsgavl
* **11 March 2011** oplæg om ebøger, CBS biblioteket
* **24 February 2011** oplæg om "ebøgernes historie og (u)muligheder". temadag på københavns kommunebiblioteker
* **27 January 2011** DF-vinterinternat om ebøger
* **2 December 2010** E-bøger - før og lige nu. Temadag om E-bøger på Gentofte Centralbibliotek, Hellerup
* **16 November 2010** “E-bøger på KB - hype, men vejen frem?”. Foredag på Forskningsnet konference 2010, Comwell Middelfart
* **9 November 2010** - Chair ved debat på uddannelsesforum 2010, bellacenteret (Dorthe Toft)
* **27 July 2010** - indslag om e-bøger i TV-avisen
* **15 June 2010** - oplæg om (e)bøgernes fremtid ved åbning af emedialab på Odense Centralbibliotek
* **19 May 2010** Oplæg om ebogens historie i forbindelse med projektet "Library bypass", Fredericia
* **6 May 2010**- foredrag om ebøger - gå-hjem-møde på Statsbiblioteket
* **9 April  2010** -  "Ebogserfaringer", oplæg for Faggruppen for medicinsk information. Glostrup Sygehus.
* **7 April 2010** - "E-bøger, status, muligheder og begrænsninger". Oplæg og paneldebat ved semesterseminar på SDU.
* **23 March 2010** - So Ein Ding, DR2 om vores udbud af ebøger og udlån af ebogslæsere
* **12 February 2010**-  oplæg for TORS om ebogslæsere, Værløse
* **17 November 2009** foredrag om ebøger for minibib, københavn
* **26 May 2009** - foredrag om ebøger - hovedbiblioteket Guldborgsund
* **30 March 2009**-  foredrag om ebøger, BF, frederiksberg.
* **19 October 2007** Folkeuniversitetet, foredragsserie om Science og Science-fiction: ”Kemien mellem stjernerne” (Den sorte diamant, København) 
* **21 June 2007** Formidling i nye medier (Den sorte diamant, København), ”InfoGalleriet, Den fremskudte formidling”
* **17 November 2008** Temadag om e-bøger, møde i Bibliotekar Forbundets Statsgruppe (BFs hus) ”Teknik: Software og hardware – læsere”
* **12 October 2007** Kreativ anvendelse af data, Temadag i DEFF, (CBS, Kilen, frederiksberg): ”Hybride data og Virtuelle verdener” 




	
