---
title: "Publications and Talks"
---
## Publications

```{r setup, echo  = FALSE, warning=FALSE, message=FALSE, results="asis"}
library(bibtex)
library(RefManageR)
pubs <- ReadBib("publications.bib")
RefManageR::NoCite(pubs)
PrintBibliography(pubs, .opts = list(style = "html",
                                     bib.style = "authoryear"))
```


## Talks

* **8. oktober 2024** Naturvidenskabelig informationssøgning. 1½ times oplæg om søgning
efter naturvidenskabelige informationskilder for folkebibliotekarer ved arrangementet
"Har du styr på den naturvidenskabelige opgave? (Vest)" ved Vejle Bibliotek. 
[slides](https://christianknudsen.info/notes/20241003-natvid-lit-search/)
* **3. oktober 2024** Naturvidenskabelig informationssøgning. 1½ times oplæg om søgning
efter naturvidenskabelige informationskilder for folkebibliotekarer ved arrangementet
"Har du styr på den naturvidenskabelige opgave? (Øst)" ved Gentofte Bibliotek.
[slides](https://christianknudsen.info/notes/20241003-natvid-lit-search/)
* **1. marts 2012** "Fagspecifikke databaser contra Web scale discovery, og om
brugen af sidstnævnte kan spores  i statistikkerne".
30 minutters oplæg på temadagen "Alt i ét? Overvejelser og praktiske erfaringer med Web Scale Discovery i Danmark".
Arrangeret af DFs forum for E-ressourcer. Den Sorte Diamant, København
* **21. februar 2012** "Causeri over e-bogen og e-bogslæsere". 1 times foredrag for Bibliotekarforeningens seniorgruppe. Det Kongelige Bibliotek, København.
* **27. oktober 2011** oplæg til forskningsbibliotekardag i Helsinki
* **2. september 2011** to-timers oplæg og debat på fredericia bibliotek
* **24. maj 2011** oplæg til møde i erhversskolernes biblioteksorening - hindsgavl
* **11. marts 2011** oplæg om ebøger, CBS biblioteket
* **24. februar 2011** oplæg om ebøgernes historie og (u)muligheder. temadag på københavns kommunebiblioteker
* **27. januar 2011** DF-vinterinternat om ebøger
* **2. december 2010** E-bøger - før og lige nu. Temadag om E-bøger på Gentofte Centralbibliotek, Hellerup
* **16. november 2010** E-bøger på KB - hype, men vejen frem? Foredag på forskningsnet konference 2010, Comwell Middelfart
* **9. november 2010** - Chair ved debat på uddannelsesforum 2010, bellacenteret (Dorthe Toft)
* **27. juli 2010** - indslag om e-bøger i TV-avisen
* **15. juni 2010** - oplæg om (e)bøgernes fremtid ved åbning af emedialab på Odense Centralbibliotek
* **19. maj 2010** Oplæg om ebogens historie i forbindelse med projektet "Library bypass", Fredericia (og hvornår var det så at dagen om library bypass blev holdt?)
* **6. maj 2010**- foredrag om ebøger - gå-hjem-møde på Statsbiblioteket
* **9. april  2010** -  Ebogserfaringer, oplæg for Faggruppen for medicinsk information. Glostrup Sygehus.
* **7. april 2010** - E-bøger, status, muligheder og begrænsninger. Oplæg og paneldebat ved semesterseminar på SDU.
* **23. marts 2010** - So Ein Ding, DR2 om vores udbud af ebøger og udlån af ebogslæsere
* **12. februar 2010**-  oplæg for TORS om ebogslæsere, Værløse
* **17. november 2009** foredrag om ebøger for minibib, københavn
* **26. maj 2009** - foredrag om ebøger - hovedbiblioteket Guldborgsund
* **30. marts 2009**-  foredrag om ebøger, BF, frederiksberg.
* **Oct. 19 2007** Folkeuniversitetet, foredragsserie om Science og Science-fiction: ”Kemien mellem stjernerne” (Den sorte diamant, København) 
* **Jun. 21 2007** Formidling i nye medier (Den sorte diamant, København), ”InfoGalleriet, Den fremskudte formidling”
* **Nov. 17 2008** Temadag om e-bøger, møde i Bibliotekar Forbundets Statsgruppe (BFs hus) ”Teknik: Software og hardware – læsere”
* **Oct. 12 2007** Kreativ anvendelse af data, Temadag i DEFF, (CBS, Kilen, frederiksberg): ”Hybride data og Virtuelle verdener” 

To gange - naturvidenskab for bibliotekarer



## der er muligvis mere her som ikke er med i ovenstående. 
Kategorien er "talks"
<strong>2012</strong>
<ul>
<li>1. juni 2012 - “eBooks from a librarian view”. Oplæg ved LM eInformation Roadshow. Børsen, København

<li>29. maj 2012 - “eBøger på Københavns Universitetsbibliotek”. Oplæg ved LM eInformation Roadshow, Aros, Aarhus.

<li>1. marts 2012 - "Fagspecifikke databaser contra Web scale discovery, og om brugen af sidstnævnte kan spores  i statistikkerne". 
30 minutters oplæg på temadagen "Alt i ét? Overvejelser og praktiske erfaringer med Web Scale Discovery i Danmark".
Arrangeret af DFs forum for E-ressourcer. Den Sorte Diamant, København

<li>21. februar 2012 - "Causeri over e-bogen og e-bogslæsere". 1 times foredrag for Bibliotekarforeningens seniorgruppe. Det Kongelige Bibliotek, København.
</ul>
<strong>2011</strong>
<ul>
<li>27. oktober 2011 - “eBooks in Denmark” - oplæg til forskningsbibliotekardag i Helsinki.
<li>2. september 2011 - To-timers oplæg og debat på fredericia bibliotek
<li>24. maj 2011- Oplæg til møde i erhversskolernes biblioteksorening - Hindsgavl
<li>11. marts 2011- Oplæg om ebøger, CBS biblioteket
<li>24. februar 2011- Oplæg om “ebøgernes historie og (u)muligheder”. Temadag på Københavns 
kommunebiblioteker
<li>27. januar 2011 - DF-vinterinternat om ebøger.</li>
</ul>
<strong>2010</strong>
<ul>
<li>2. december 2010 - “E-bøger - før og lige nu.” Temadag om E-bøger på Gentofte Centralbibliotek, Hellerup

<li>16. november 2010 - “E-bøger på KB - hype, men vejen frem?”. Foredag på Forskningsnet konference 2010, Comwell Middelfart

<li>9. november  2010 - Chair ved debat på Uddannelsesforum 2010, Bellacenteret, København.

<li>2. november 2010 - Oplæg om ebogens historie Library bypass konference. Odense

<li>27. juli 2010 - Indslag om e-bøger i TV-avisen

<li>15. juni 2010 - Oplæg om (e)bøgernes fremtid ved åbning af emedialab på Odense Centralbibliotek

<li>19. maj 2010 Oplæg om ebogens historie i forbindelse med projektet "Library bypass", Fredericia 

<li>6. maj 2010 - Foredrag om ebøger - gå-hjem-møde på Statsbiblioteket

<li>9. april 2010 - “Ebogserfaringer”, oplæg for Faggruppen for medicinsk information. Glostrup Sygehus.

<li>7. april 2010 - “E-bøger, status, muligheder og begrænsninger.” Oplæg og paneldebat ved semesterseminar på SDU.

<li>23. marts 2010 - So Ein Ding, DR2, om bibliotekets udbud af ebøger og udlån af ebogslæsere

<li>12. februar 2010  - Oplæg for TORS-KU om ebogslæsere, Værløse
</ul>

## Og her diverse skrammel fra et ældre site - kategori publikationer

<ul>
	<li>Redaktør af (ebogsudgaven 2015) <em>Oxygen - Et skuespil i 20 scener - Et grundstofs opdagelseshistorie</em>. <a href="http://materialeplatform.emu.dk/materialer/bogkort/85985119" target="_blank">Link</a></li>
	<li>Redaktør af <i>DF’s ebogsbarometer 2012</i>. <a href="http://dfdf.dk/index.php/rapporter3/doc_download/110-df-s-ebogsbarometer-2012" target="_blank">Link</a></li>
	
    	<li>Redaktør af <i>DF’s ebogsbarometer 2011</i>. <a href="http://dfdf.dk/index.php/rapporter3/doc_download/27-df-s-ebogsbarometer-2011-revideret-udgave" target="_blank">Link</a></li>
	<li>Senning, A. &amp; Knudsen, C. B. (2010), 'Stereokemi for viderekomne eller røre i andedammen', <i>Dansk Kemi</i> <b>91</b>(3), 30-31. <a href="http://techmedia.swiflet.com/tm/dak/31/1/" target="_blank">Link</a></li>
	<li>Jensen, J. L. &amp; Knudsen, C. B. (2010), 'Et bibliotek uden bøger?', <i>Revy</i> <b>33</b>(6), 4-5. <a href="http://rauli.cbs.dk/index.php/revy/article/view/3094/3209" target="_blank">Link</a></li>
	<li>Knudsen, C. B. (2010), 'Smuk som en Star Trek-PADD', <i>Subspace</i> <b>15</b>(2), 26-27.</li>
	<li>Knudsen, C. B. (2010), 'Der er intet let ved e-bøger', <i>Revy</i> <b>33</b>(2), 16-18. <a href="http://issuu.com/revy/docs/nummer_2_-_2010_for_web" target="_blank">Link</a></li>
	<li>Hansen, K. S.; Knudsen, C. B.; Dorch, B. F. &amp; Olsen, N. A. (2008), 'Forskningsbibliotekerne og intranet', <i>DF Revy</i> <b>31</b>(7), 12-13. <a href="http://ej.lib.cbs.dk/index.php/dfrevy/article/viewFile/2244/2233">http://ej.lib.cbs.dk/index.php/dfrevy/article/viewFile/2244/2233</a></li>
	<li>Knudsen, C. (2008), 'Illegale lærebøker', <i>Bibliotekaren</i> <b>16</b>(11), 6-8. <a href="http://www.bibforb.no/filestore/BIKA/BIKA/bk0811.pdf">http://www.bibforb.no/filestore/BIKA/BIKA/bk0811.pdf</a></li>
	<li>Knudsen, C. (2008), 'Illegale lærebøger', <i>DF Revy</i> <b>31</b>(6), 10-11. <a href="http://ej.lib.cbs.dk/index.php/dfrevy/article/download/2141/2125">http://ej.lib.cbs.dk/index.php/dfrevy/article/download/2141/2125</a></li>
	<li>Knudsen, C.; Kalampounias, A.; Fehrmann, R. &amp; Boghosian, S. (2008), 'Thermal Dissociation of Molten KHSO4: Temperature Dependence of Raman Spectra and Thermodynamics', <i>J. Phys. Chem. B</i> <b>112</b>(38), 11996-12000. <a href="http://pubs.acs.org/cgi-bin/abstract.cgi/jpcbfk/asap/abs/jp801853z.html">http://pubs.acs.org/cgi-bin/abstract.cgi/jpcbfk/asap/abs/jp801853z.html</a></li>
	<li>Olsen, N. A.; Knudsen, C. B. &amp; Nielsen, S. S. v. B. (2008), 'Forskningsbiblioteket i Second Life', <i>DF Revy</i> <b>31</b>(3), 12-13. <a href="http://rauli.cbs.dk/index.php/revy/article/view/1726/1750">http://rauli.cbs.dk/index.php/revy/article/view/1726/1750</a></li>
	<li>Knudsen, C. B. (2008), 'Anm. af "Kemisk Ordbog Online"', <i>Dansk Kemi</i> <b>89</b>(6/7), 6. <a href="http://techmedia.swiflet.com/tm/dak/18/1/">http://techmedia.swiflet.com/tm/dak/18/1/</a></li>
	<li>Knudsen, C. B. (2007), 'Second Life. Bristet boble eller beskæftigelsesterapi?', <i>DF Revy</i> <b>30</b>(7), 28. <a href="http://rauli.cbs.dk/index.php/revy/article/view/1304/1298">http://rauli.cbs.dk/index.php/revy/article/view/1304/1298</a></li>
	<li>Knudsen, C. B. &amp; Christophersen, C. (2007), 'Bogen der blev væk', <i>Dansk Kemi</i> <b>88</b>(9), 44. <a href="http://techmedia.swiflet.com/tm/dak/9/1/">http://techmedia.swiflet.com/tm/dak/9/1/</a></li>
	<li>Knudsen, C. B. (2007), 'InfoGalleriet - den fremskudte formidling', <i>DF Revy</i> <b>30</b>(5), 4-5. <a href="http://rauli.cbs.dk/index.php/revy/article/view/977/989">http://rauli.cbs.dk/index.php/revy/article/view/977/989</a></li>
	<li>Knudsen, C. B. (2006), 'Anm. af "The Physics of Star Trek"', <i>Subspace</i> <b>11</b>(3), 23</li>
</ul>