---
title: "CiRcle aRt"
subtitle: "indsæt subtitle"
author: "Christian Knudsen"
visible: "false" # sæt til noget andet når oplægget/noten er færdigt
categories:
  - kategori 1
  - kategori 2
date: 2025-10-23
toc: true
image: ""
---



```{r}
library(tidyverse)
library(ggforce)
geom_circle()

```


3 streger - major
hver under indelt med en mellem
som er underinddelt med 1 minor

På begge leder

1,2,3

```{r}
n <- 3
cirkler <- function(n = 3, seed = NULL) {
  set.seed(seed)
  z <- seq(1, 3, 0.25)
  x0 <- sample(z, n, replace  =TRUE)
  y0 <- sample(z, n, replace = TRUE)
  r <-  sample(c(0.25, 1, 0.25), n, replace = TRUE)
  colors <- sample(1:3, n, replace = TRUE) |> factor()
  df <- tibble(x0 = x0, y0 = y0, r = r)
  
  ggforce::geom_circle(
    data = df,
    mapping = aes(x0 = x0, y0 = y0, r = r, color = colors),
    fill = NA,
    inherit.aes = FALSE
  )
}
```


```{r}
lines <- function(n = 5, seed = NULL){
   z <- seq(1, 3, 0.25)
  x0 <- sample(z, n, replace = TRUE)
  y0 <- sample(z, n, replace = TRUE)
  l <-  sample(c(0.25, 3, 0.25), n, replace = TRUE)
  xy <- sample(c(0,1), n, replace = TRUE)
  dir <- sample(c(-1,1), n, replace = TRUE)
  colors <- sample(1:3, n, replace = TRUE) |> factor()
tibble(x0 = x0, y0=y0, l = l, x = xy, dir = dir, color = colors) |> 
  mutate(y = as.numeric((x == 0))) |> 
  mutate(x1 = x0 + x * dir * l,
         y1 = y0 + y * dir * l) |>
  geom_segment(mapping = aes(x = x0, y = y0, xend = x1, yend = y1, color = colors), inherit.aes = FALSE)

}
```


```{r}
# expand.grid(x = seq(1,3,0.25), y = seq(1,3,0.25))  
ggplot() +
  cirkler(n = 5, seed = 666) +
  lines(n = 11, seed = 666) +
  coord_cartesian(xlim = c(0,4), ylim = c(0,4))  +
  theme_void()+
  theme(legend.position = "none",
        plot.background = element_rect(color = "black",
        fill = "black")) +
  annotate("text", x = 3.5, y = -0.1,
            size = 3,
            label = "nusseaRt, seed = 42", 
            color = "white")

  ggsave("notes/20251023-circle_art/cirkler.png")
```




expand.grid(x = seq(1,3,0.25), y = seq(1,3,0.25)) |>
  ggplot(aes(x, y)) +
#  geom_point() +
  cirkler(n = 7) +
  coord_cartesian(xlim = c(0,4), ylim = c(0,4))  +
  theme_void() +
  theme(legend.position  = "none") 

p
ggsave("cirkler.png", plot = p)

